# Generated by Django 6.0.3 on 2026-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idempotencykey',
            old_name='endpoint',
            new_name='request_path',
        ),
        migrations.RemoveField(
            model_name='idempotencykey',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='idempotencykey',
            name='user',
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='request_method',
            field=models.CharField(default='POST', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='response_code',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='response_body',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
