PAYMENT_INTENT_CREATED = "PAYMENT_INTENT_CREATED"

PAYMENT_CHECKOUT_CREATED = "PAYMENT_CHECKOUT_CREATED"

PAYMENT_APPROVED = "PAYMENT_APPROVED"

PAYMENT_FAILED = "PAYMENT_FAILED"

PAYMENT_RECONCILED = "PAYMENT_RECONCILED"

WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"

PAYMENT_RECONCILIATION_DISCREPANCY = "PAYMENT_RECONCILIATION_DISCREPANCY"