# Generated by Django 6.0.3 on 2026-03-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='provider_status',
            field=models.CharField(default='NOT_APPLICABLE', max_length=50),
        ),
    ]
