# Generated by Django 6.0.3 on 2026-03-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallettransaction_checkout_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rail', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MERCADO_PAGO', 'Mercado Pago')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('destination_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet')),
            ],
        ),
    ]
