# Generated by Django 6.0.3 on 2026-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_walletwithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='ARS', max_length=15),
        ),
    ]
